import { test, expect } from "@playwright/test";
import { get } from "http";

test.describe(' Testing all the API Calls', () => {

    test(' Testing of POST Call and GET Call', async ({ request }) => {

        const body = {
            name: "Apple MacBook Pro 16",
            data: {
                year: 2019,
                price: 1849.99,
                "CPU model": "Intel Core i9",
                "Hard disk size": "1 TB"
            }
        };
        const response = await request.post('https://api.restful-api.dev/objects', { data: body, ignoreHTTPSErrors: true });
        const actualResponse = await response.json();
        console.log(actualResponse);

        const id = actualResponse.id;
        console.log(`ID Generated by POST call is ${id}`)

        const getResponse = await request.get(`https://api.restful-api.dev/objects?id=${id}`)
        const actualGetResponse = await getResponse.json()

        console.log(`Response of the ID is ${JSON.stringify(actualGetResponse)}`);

    })

}
)


