name: Greetings

on:
  workflow_dispatch:
   inputs:
        environemnt: 
          default: st2
          required: true

        

env:
  cloud: google-cloud

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment files
        run: echo $cloud ${{ vars.PROJECT_ID}} ${{ github.repository}} ${{ secrets.password}} Environment is $ {{ inputs.environment}}
